"""Configuration constants for the dungeon game."""

# Board configuration
DEFAULT_BOARD_SIZE = 101
DEFAULT_VIEW_SIZE = 7
DEFAULT_CELL_SIZE = 90

# Zoom levels
ZOOM_LEVELS = [7, 11, 21, 51, DEFAULT_BOARD_SIZE]
DEFAULT_ZOOM_INDEX = 0

# Rendering
FIXED_WINDOW_SIZE = DEFAULT_VIEW_SIZE * DEFAULT_CELL_SIZE  # 630x630 pixels

# Colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GRAY_DARK = (80, 80, 80)
COLOR_GRAY_LIGHT = (150, 150, 150)

# Lighting
BASE_BRIGHTNESS_ENTRANCE = 20
BASE_BRIGHTNESS_EXIT = 0
BASE_BRIGHTNESS_LINES_ENTRANCE = 50
BASE_BRIGHTNESS_LINES_EXIT = 0
MAX_TORCH_BRIGHTNESS = 130
TORCH_BRIGHTNESS_PER_UNIT = 31

# Blood and effects
BLOOD_DARKENING_FACTOR = 0.5  # 50% del gradiente

# Generation
MAX_GENERATION_ATTEMPTS = 10
